### PR TITLE
Application with session as authenticationType can't logout

### LINKED ISSUE #284: Application with session as authenticationType can't logout
When choosing `session` for authenticationType, we can't logout.
https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/templates/vue/src/main/webapp/app/account/account.service.ts.ejs#L31

I think we need to clear the cookie when logout.
That's probably why protractor tests failed in this PR: https://github.com/jhipster/jhipster-vuejs/pull/282

### PR DESCRIPTION
**Pull request by sahbi-ktifa**
Fix #284
Merge loginModalService/loginService into one to avoid complexity

-   Please make sure the below checklist is followed for Pull Requests.

-   [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-vuejs/pull_requests) are green
-   [x] Tests are added where necessary
-   [x] Documentation is added/updated where necessary
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-vuejs/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
It seems to have 1 npm test which failed

File: generators/client/templates/vue/src/main/webapp/app/account/activate/activate.component.ts.ejs [hunk 1]
```diff
@@ -30,6 +32,6 @@ export default class Activate extends Vue {
   }
 
   public openLogin(): void {
-      this.loginModalService().openLogin((<any>this).$root);
+      this.loginService().openLogin((<any>this).$root);
```
Comment (pascalgrimaud) [inline generators/client/templates/vue/src/main/webapp/app/account/activate/activate.component.ts.ejs]: the method openLogin won't exist for OAuth2

Comment (sahbi-ktifa) [reply generators/client/templates/vue/src/main/webapp/app/account/activate/activate.component.ts.ejs]: This component should not even been here with oauth2. I changed this.
